import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const browser=await chromium.launch();const base=process.env.SITE_BASE||'http://127.0.0.1:4879';await mkdir('renders',{recursive:true});
for(const width of [320,390,768,1024,1440])for(const scheme of ['dark','light']){
 const context=await browser.newContext({viewport:{width,height:1000},colorScheme:scheme,reducedMotion:'reduce',permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.locator('html').getAttribute('data-theme'),scheme);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width} ${scheme}`);
 await page.screenshot({path:`renders/refresh-${scheme}-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:`Switch to ${scheme==='dark'?'light':'dark'} mode`}).click();await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),scheme==='dark'?'light':'dark');
 if(width<=1024){await page.getByRole('button',{name:'Open menu',exact:true}).click();assert(await page.locator('#nav-menu').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('#nav-menu').isVisible(),false);await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.locator('#nav-menu').getByRole('link',{name:'Framework'}).click();assert.equal(await page.locator('#nav-menu').isVisible(),false);assert.equal(await page.locator('main').evaluate(e=>e.inert),false);}
 await page.getByRole('tab',{name:'CLI',exact:true}).click();assert(await page.locator('#example-cli').isVisible());await page.getByRole('tab',{name:'CLI',exact:true}).press('ArrowRight');assert(await page.locator('#example-api').isVisible());
 await page.getByRole('button',{name:'Classify flowers',exact:true}).click();assert.match(await page.locator('#message').inputValue(),/Classify flowers/);
 await page.route('https://design.zer.foo/api/design',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({message:'Tell me the target column.'})}));await page.getByRole('button',{name:'Design with me',exact:true}).click();await page.getByText('Tell me the target column.',{exact:true}).waitFor();assert(await page.locator('#chat-transcript').isVisible());const transcriptBox=await page.locator('#chat-transcript').boundingBox();const inputBox=await page.locator('#message').boundingBox();assert(transcriptBox.y+transcriptBox.height<=inputBox.y,'Conversation must sit above the reply input');
 await page.unroute('https://design.zer.foo/api/design');await page.route('https://design.zer.foo/api/design',route=>route.fulfill({status:429,contentType:'application/json',body:JSON.stringify({error:'Hosted chat has reached its spending limit. Continue locally.'})}));await page.locator('#message').fill('species');await page.getByRole('button',{name:'Design with me',exact:true}).click();await page.getByRole('alert').filter({hasText:'spending limit'}).waitFor();assert.equal(await page.locator('#message').inputValue(),'species');assert.equal(await page.locator('#send').isDisabled(),false);await page.getByRole('button',{name:'Copy instruction',exact:true}).click();await page.waitForFunction(()=>document.getElementById('copied').textContent==='Copied');
 assert.deepEqual(errors,[]);await context.close();
}
const page=await browser.newPage({reducedMotion:'no-preference'});await page.goto(base);await page.waitForFunction(()=>document.documentElement.classList.contains('hero-ready'));assert.equal(await page.locator('h1').evaluate(e=>getComputedStyle(e).opacity),'1');await browser.close();console.log('Landing: 10 theme/viewport combinations, menu, persistence, code tabs, live-chat UI, budget fallback, clipboard and entrance passed.');
