const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'@playwright/test');
const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1200,height:630},deviceScaleFactor:1});await page.goto('http://127.0.0.1:4879/');await page.evaluate(()=>{document.body.innerHTML=`<main style="width:1200px;height:630px;background:#151111;position:relative;overflow:hidden;padding:60px 72px"><div style="position:absolute;left:-250px;top:-650px;width:1700px;height:900px;border-radius:50%;border:1px solid #f5c4b1;box-shadow:0 8px 32px #edaa97,0 24px 70px #edaa9766"></div><div style="position:relative"><div class="wordmark"><img src="/zerfoo.svg" width="40" height="40" alt="">zerfoo</div><p style="font:12px var(--mono);letter-spacing:2px;color:#edaa97;margin-top:75px">OPEN SOURCE. OPEN POSSIBILITIES.</p><h1 style="font-size:94px;letter-spacing:-6px;line-height:1.02;margin-top:22px">AI inference.<br><span style="color:#edaa97">Native to Go.</span></h1><p style="color:#c8b6ad;margin-top:28px;font-size:20px">Your models. Your infrastructure. Your Go code.</p><div style="display:flex;justify-content:space-between;font:11px var(--mono);letter-spacing:1px;margin-top:38px;color:#b49f93"><span>ZERFOO.FEZA.AI</span><span>GO NATIVE / APACHE 2.0</span></div></div></main>`});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'static/social-card.png'});
await page.goto('http://127.0.0.1:4879/');await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'renders/r1-mobile-hero.png'});
await page.setViewportSize({width:512,height:512});
await page.evaluate(()=>{document.body.innerHTML='<main style="width:512px;height:512px;display:grid;place-items:center;background:#101011"><img src="/zerfoo.svg" width="320" height="320" alt="Zerfoo"></main>'});
await page.locator('img').evaluate(img=>img.decode());
const mark=await page.screenshot();fs.writeFileSync('static/logo.png',mark);fs.writeFileSync('static/zerfoo.png',mark);
await browser.close();})();
